#
# buildspec.yml
#

version: 0.2

env:
  variables:
    target_assets: apps/site-mock/node_modules/
    target_bucket: unpkg.internal.lib.virginia.edu
    target_root: web-components
    package_file: apps/site-mock/package.json

phases:
  install:
    runtime-versions:
      nodejs: 16
#    commands:

  pre_build:
    commands:
      - BUILD_VERSION=$(date --date="@$(echo $CODEBUILD_START_TIME | cut -c1-10)" +"%Y%m%d%H%M%S")
      - PACKAGE_VERSION=$(grep "\"version\":" ${package_file} | awk '{print $2}' | tr -d "\",")
      - ASSET_VERSION=${PACKAGE_VERSION}-${BUILD_VERSION}
      - COMMIT_TAG=gitcommit-$CODEBUILD_RESOLVED_SOURCE_VERSION
      - versioned_target=${target_bucket}/${target_root}/${ASSET_VERSION}
      - latest_target=${target_bucket}/${target_root}/latest

  build:
    commands:
      - npm install -g pnpm
      - pnpm install --no-frozen-lockfile
      - npx turbo run build --filter=site-mock
      - echo "Uploading to s3://${versioned_target}"
      - aws s3 cp ${target_assets} s3://${versioned_target} --recursive --quiet
      - echo "Cleaning s3://${latest_target}"
      - aws s3 rm s3://${latest_target} --recursive --quiet
      - echo "Uploading to s3://${latest_target}"
      - aws s3 cp ${target_assets} s3://${latest_target} --recursive --quiet
      - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths ${latest_target}

#  post_build:
#    commands:

#
# end of file
#
