#
# buildspec.yml
#

version: 0.2

env:
  variables:
    target_assets: packages/cdn-builds/build/
    target_bucket: unpkg.internal.lib.virginia.edu
    target_root: web-components
    package_file: packages/cdn-builds/package.json

phases:
  install:
    runtime-versions:
      nodejs: 16
#    commands:

  pre_build:
    commands:
      - published_version=$(git describe --tags --abbrev=0 --first-parent --match "cdn-v[0-9]*" || echo 0)
      - published_target="${target_bucket}/${target_root}/${published_version}"
      - latest_target=${target_bucket}/${target_root}/latest

  build:
    commands:
      - npm install -g pnpm
      - pnpm install --no-frozen-lockfile
      - pnpm turbo run build --filter=cdn-builds
      - echo "Uploading to s3://${latest_target}"
      - aws s3 sync ${target_assets} s3://${latest_target} --delete --quiet
      - |
        if [ $published_version ]; then
          echo "Syncing s3://${latest_target} -> s3://${published_target}"
          aws s3 sync s3://${latest_target} s3://${published_target} --delete --quiet
        else
          echo "No published tag detected on this commit"
        fi
      - echo "Invalidating CDN cache"
      - AWS_MAX_ATTEMPTS=10 aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths "/${target_root}/latest"

#  post_build:
#    commands:

#
# end of file
#
