#
# buildspec.yml
#

version: 0.2

env:
  variables:
    deploy_bucket: default-lambda-deploy

phases:
  install:
    runtime-versions:
      nodejs: 20
#    commands:

  pre_build:
    commands:
      - BUILD_VERSION=$(date --date="@$(echo $CODEBUILD_START_TIME | cut -c1-10)" +"%Y%m%d%H%M%S")
      - COMMIT_TAG=gitcommit-${CODEBUILD_RESOLVED_SOURCE_VERSION}

  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/apps/log-stats
      - npm install -g rimraf
      - npm install
      - npm run build
      #
      # copy log-stats target
      - aws s3 cp ${CODEBUILD_SRC_DIR}/apps/log-stats/function.zip s3://${deploy_bucket}/${BUILD_VERSION}/cdn-reporter/function.zip --quiet
      #
      # create the git commit tag file
      #
      - touch ${CODEBUILD_SRC_DIR}/${COMMIT_TAG}.git
      - aws s3 cp ${CODEBUILD_SRC_DIR}/${COMMIT_TAG}.git s3://${deploy_bucket}/${BUILD_VERSION}/${COMMIT_TAG}.git --quiet
      #
      # make the latest folder
      #
      - aws s3 sync s3://${deploy_bucket}/${BUILD_VERSION} s3://${deploy_bucket}/latest --delete --quiet

#  post_build:
#    commands:

#
# end of file
#
